### ISSUE TITLE
open wiki for detailed set up instructions?

### ISSUE THREAD

**Issue by benkoshy** [phenax/esbuild-plugin-elm#12]
Hi there Akshay @phenax 

Thank you for sharing your library.

I set up a working example on a rails app. it was a little bit tricky: i feel some pointers would be useful for the general community -  would you be against opening up the wiki for these rails set up instructions to be documented? If you deem it useful, I can easily add them in.

chrs, 
Ben

**Comment by phenax** [comment]
Interesting idea. However, I think this plugin by itself isn't complex enough for many nuances. Any guide on this would be too specific to either esbuild or elm. But I do think a general guide on setting up an elm project with esbuild would be incredibly helpful. If it can be turned into a blog post on dev.to or somewhere, I would love to link it in the readme!

**Comment by benkoshy** [comment]
> But I do think a general guide on setting up an elm project with esbuild would be incredibly helpful. If it can be turned into a blog post on dev.to or somewhere, I would love to link it in the readme

Many rails users will be switching to es-build over the next few months. Your plugin will be incredibly useful to this community - and I imagine others:  i can do a rails specific tutorial on setting up elm with esbuild (as well as initialising the javascript), and leave it to your absolute discretion whether to link it or not. There is no loss from my side in doing so, because i have no doubt it will be useful to the wider community.

Thanks again for the library. (I can see that NoRedInk have forked your repo, which speaks volumes for its usefulness)

edit: i'll post a pr to the readme (in a few days) with the link: if you are against it feel free to close or cancel without compunction etc.

**Comment by benkoshy** [comment]
Closing in favour of #13.
