### ISSUE TITLE
esbuild recompiles all Elm main files even tho only one changed

### ISSUE THREAD

**Issue by jjant** [phenax/esbuild-plugin-elm#15]
I'm compiling about 20 main files with esbuild in watch mode, and whenever I change a file, all of them get recompiled. This doesn't happen in webpack.
Is there an option I should look into? Or maybe this is not implemented yet?

**Comment by jjant** [comment]
I think the issue may be that the plugin doesn't implement caching at all?

**Comment by phenax** [comment]
Fixed by #17
